server:
  port: 8080
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bdm317877418.my3w.com:3306/bdm317877418_db
    username: bdm317877418
    password: bdm317877418
    